export const COMPANIES = [
  {
    id: 1,
    companyName: 'Coinbase',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/coinbase_company_logo_0b832f7fce.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/coinbase_company_logo_4e41766ac9.webp',
  },
  {
    id: 2,
    companyName: 'Binance',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/binance_company_logo_82772d9680.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/binance_company_logo_8757bd0823.webp',
  },
  {
    id: 3,
    companyName: 'Near',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/near_company_logo_2a0eb9930d.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/near_company_logo_aea1d13059.webp',
  },
  {
    id: 4,
    companyName: 'GlobalID',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Globali_D_6abc8eabdc.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/globalid_70eef68a19.webp',
  },
  {
    id: 5,
    companyName: 'Consensys',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/consensys_company_logo_c428d48fe0.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/consensys_company_logo_8b5756c9da.webp',
  },
  {
    id: 6,
    companyName: 'Okcoin',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/okcoin_company_logo_8443e8f883.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/okcoin_company_logo_210887a24a.webp',
  },
  {
    id: 7,
    companyName: 'Chainlink Labs',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/chainlink_labs_company_logo_edf5ad4ebb.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/chainlink_labs_company_logo_a6b79b8d40.webp',
  },
  {
    id: 8,
    companyName: 'Chainalysis',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/chainalysis_company_logo_4bad7c90b3.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/chainalysis_company_logo_8a965f0c81.webp',
  },
  {
    id: 9,
    companyName: 'Ripple',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/ripple_company_logo_a804e73302.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/ripple_company_logo_54309f93ef.webp',
  },
  {
    id: 10,
    companyName: 'Bit Go',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/bitgo_company_logo_99269c5337.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/bitgo_company_logo_3827282e43.webp',
  },
  {
    id: 11,
    companyName: 'Wintermute',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/wintermute_company_logo_c85a1ed78f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/wintermute_company_logo_887760be94.webp',
  },
  {
    id: 12,
    companyName: 'Kraken',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/kraken_company_logo_11c21e27a8.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/kraken_company_logo_da86be4805.webp',
  },
  {
    id: 13,
    companyName: 'Gsr',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/gsr_company_logo_6e2efe8b82.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/gsr_company_logo_856d7c5443.webp',
  },
  {
    id: 14,
    companyName: 'Swiss Borg',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/swissborg_company_logo_803773a11e.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/swissborg_company_logo_965024e014.webp',
  },
  {
    id: 15,
    companyName: 'Recur',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/recur_company_logo_1e72ad5f7a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/recur_company_logo_b6da75ea8f.webp',
  },
  {
    id: 16,
    companyName: 'Bitcoin Depot',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/bitcoin_depot_company_logo_d65d16ab96.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/bitcoin_depot_company_logo_bba2f7f774.webp',
  },
  {
    id: 17,
    companyName: 'Figure',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/figure_company_logo_ede3fa3628.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/figure_company_logo_2fbde98d5f.webp',
  },
  {
    id: 18,
    companyName: 'Candy',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/candy_company_logo_5da3abb087.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/candy_company_logo_d1dafee5cf.webp',
  },
  {
    id: 19,
    companyName: 'Blockchain',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/blockchain_company_logo_91e3d22774.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/blockchain_company_logo_37f66170ff.webp',
  },
  {
    id: 20,
    companyName: 'dYdX',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/d_Yd_X_0698f75c05_b493643be8.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/d_Yd_X_0698f75c05.webp',
  },
  {
    id: 21,
    companyName: 'Bitfury',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/bitfury_company_logo_ec8d81125d.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/bitfury_company_logo_0749a3f2b0.webp',
  },
  {
    id: 22,
    companyName: 'Bit Mex',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/bitmex_company_logo_a3f59e9586.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/bitmex_company_logo_59c7ccfd74.webp',
  },
  {
    id: 23,
    companyName: 'Polygon',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/polygon_company_logo_542d3d3b3a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/polygon_company_logo_1a8549ef6c.webp',
  },
  {
    id: 24,
    companyName: 'Ok Ex',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/ok_ex_company_logo_c457939a7b.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/ok_ex_company_logo_4d4dc27392.webp',
  },
  {
    id: 25,
    companyName: 'Alchemy',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/alchemy_company_logo_4ee9d989d1.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/alchemy_company_logo_c633409096.webp',
  },
  {
    id: 26,
    companyName: 'Immutable',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/immutable_company_logo_5175984c05.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/immutable_company_logo_5507f64b52.webp',
  },
  {
    id: 27,
    companyName: 'Parity Technologies',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/parity_company_logo_a827cddf51.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/parity_company_logo_bdccbe5950.webp',
  },
  {
    id: 28,
    companyName: 'Open Sea',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/open_sea_company_logo_365d8f417f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/open_sea_company_logo_2a04af9cfb.webp',
  },
  {
    id: 29,
    companyName: 'Ianuly',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Ianuly_45bb61bbf0.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Ianuly_a26fcef2bb.webp',
  },
  {
    id: 30,
    companyName: 'Block Fi',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/block_fi_company_logo_a5886f4625.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/block_fi_company_logo_52481cec4b.webp',
  },
  {
    id: 31,
    companyName: 'Syndica',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Syndica_b1aedc7922.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Syndica_95754c020d.webp',
  },
  {
    id: 32,
    companyName: 'Woo Network',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/woonetwork_company_logo_05ff560d5f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/woonetwork_company_logo_d7916c85b5.webp',
  },
  {
    id: 33,
    companyName: 'Blockdaemon',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/blockdaemon_company_logo_272f1822e4.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/blockdaemon_company_logo_5121368537.webp',
  },
  {
    id: 34,
    companyName: 'Coindesk',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/coindesk_company_logo_cd9a05b986.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/coindesk_company_logo_4e610fb18a.webp',
  },
  {
    id: 35,
    companyName: 'Toucan',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Toucan_dcf34f5b85.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Toucan_dcf34f5b85_1e2f0564eb.webp',
  },
  {
    id: 36,
    companyName: 'Clearmatics',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Clearmatics_30aa26eb9f_924becab97.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Clearmatics_30aa26eb9f.webp',
  },
  {
    id: 37,
    companyName: 'Moon Pay',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/moon_pay_company_logo_99324ac15a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/moon_pay_company_logo_12427212e4.webp',
  },
  {
    id: 38,
    companyName: 'Paxful',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/paxful_company_logo_2a61567daa.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/paxful_company_logo_401436620b.webp',
  },
  {
    id: 39,
    companyName: 'Coin Flip',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/coin_flip_company_logo_d015cf51b7.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/coin_flip_company_logo_8304fb0093.webp',
  },
  {
    id: 40,
    companyName: 'Protocol Labs',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/protocol_labs_company_logo_f42161d137.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/protocol_labs_company_logo_f9092cd973.webp',
  },
  {
    id: 41,
    companyName: 'Ava Labs',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/ava_labs_company_logo_4b1ba6112c.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/ava_labs_company_logo_69f8c1c295.webp',
  },
  {
    id: 42,
    companyName: 'Dfinity',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/dfinity_company_logo_3268f04b92.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/dfinity_company_logo_8a0f24665e.webp',
  },
  {
    id: 43,
    companyName: 'Steel Perlot',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Steel_Perlot_cd0ea1f1b5.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Steel_Perlot_7f47154163.webp',
  },
  {
    id: 44,
    companyName: 'Figment',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/figment_company_logo_d392774b71.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/figment_company_logo_73f23cff0f.webp',
  },
  {
    id: 45,
    companyName: 'Stellar',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/stellar_company_logo_1fa093ed30.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/stellar_company_logo_05faf60f4b.webp',
  },
  {
    id: 46,
    companyName: 'Bittrex',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/bittrex_company_logo_be004d9d1b.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/bittrex_company_logo_a2b4577a1a.webp',
  },
  {
    id: 47,
    companyName: 'Iov Labs',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/iov_labs_company_logo_a90ad33c4b.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/iov_labs_company_logo_793524ab19.webp',
  },
  {
    id: 48,
    companyName: 'Global Income Coin',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Global_Income_Coin_8e649be37a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Global_Income_Coin_98013de06d.webp',
  },
  {
    id: 49,
    companyName: 'Cake Pte Ltd',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/cake_pte_ltd_company_logo_870348074b.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/cake_pte_ltd_company_logo_1d875127af.webp',
  },
  {
    id: 50,
    companyName: 'The Block',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/the_block_company_logo_84b4847c1f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/the_block_company_logo_cb4dc81e8d.webp',
  },
  {
    id: 51,
    companyName: 'Shakepay',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/shakepay_company_logo_964767041a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/shakepay_company_logo_88a22acb2c.webp',
  },
  {
    id: 52,
    companyName: 'Tron',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/tron_company_logo_6fcdab142f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/tron_company_logo_de685315e4.webp',
  },
  {
    id: 53,
    companyName: 'Amun 21 Shares',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/amun_21_shares_company_logo_96ac608b86.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/amun_21_shares_company_logo_e5d8c6f96c.webp',
  },
  {
    id: 54,
    companyName: 'C Labs',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/c_labs_company_logo_e385d91a7f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/c_labs_company_logo_7f682e07b8.webp',
  },
  {
    id: 55,
    companyName: 'Worldcoin.Org',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/worldcoinorg_company_logo_7b4c821e89.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/worldcoinorg_company_logo_bc3c6c2642.webp',
  },
  {
    id: 56,
    companyName: 'Maple',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Maple_5d1aad066c.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Maple_62cb390f59.webp',
  },
  {
    id: 57,
    companyName: 'Localcoin',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/localccoin_company_logo_b5750627be.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/localccoin_company_logo_fa0648bca7.webp',
  },
  {
    id: 58,
    companyName: 'Paradigm',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/paradigm_company_logo_b38aad54f3.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/paradigm_company_logo_e0f4aa0869.webp',
  },
  {
    id: 59,
    companyName: 'Coin List',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/coinlist_company_logo_6799bf25be.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/coinlist_company_logo_33bc8f695e.webp',
  },
  {
    id: 60,
    companyName: 'Change',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/change_company_logo_22bc4e9276.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/change_company_logo_ac3a73ad89.webp',
  },
  {
    id: 61,
    companyName: 'Coin Gecko',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/coin_gecko_company_logo_a1b4427fe5.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/coin_gecko_company_logo_c013444c23.webp',
  },
  {
    id: 62,
    companyName: 'Rarible',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/rarible_company_logo_a0bffdea8e.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/rarible_company_logo_7a6a53693d.webp',
  },
  {
    id: 63,
    companyName: 'Mojito',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Mojito_05de7207b4.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Mojito_6d8fc0d75e.webp',
  },
  {
    id: 64,
    companyName: 'Public',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/public_company_logo_700b32f017.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/public_company_logo_85dd933b07.webp',
  },
  {
    id: 65,
    companyName: 'Tendermint',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/tendermint_company_logo_a4a53df8a9.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/tendermint_company_logo_7e82b1b0ae.webp',
  },
  {
    id: 66,
    companyName: 'Bitwise Asset Management',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/bitwise_asset_management_company_logo_f6eff25203.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/bitwise_asset_management_company_logo_96f3781564.webp',
  },
  {
    id: 67,
    companyName: 'Ledger',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/ledger_company_logo_92854e4f11.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/ledger_company_logo_d9470365f2.webp',
  },
  {
    id: 68,
    companyName: 'Vauld',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/vauld_company_logo_d8c05dd442.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/vauld_company_logo_3dba6ce7c5.webp',
  },
  {
    id: 69,
    companyName: 'Autograph',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/autograph_company_logo_63ded6845b.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/autograph_company_logo_c90f150e65.webp',
  },
  {
    id: 70,
    companyName: 'Wintermute',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/wintermute_company_logo_c85a1ed78f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/wintermute_company_logo_887760be94.webp',
  },
  {
    id: 71,
    companyName: 'Sense',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Sense_02991ca60f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Sense_fd7300f107.webp',
  },
  {
    id: 72,
    companyName: 'Foundry',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/foundry_company_logo_dd54685035.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/foundry_company_logo_ccd9519d62.webp',
  },
  {
    id: 73,
    companyName: 'Aragon',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Aragon_bf7942c51d.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Aragon_7bc330e9bd.webp',
  },
  {
    id: 74,
    companyName: 'Eco',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/eco_company_logo_2078db2986.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/eco_company_logo_fa8e402c3c.webp',
  },
  {
    id: 75,
    companyName: 'Centrifuge',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Centrifuge_dba726369e.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Centrifuge_61900b0710.webp',
  },
  {
    id: 76,
    companyName: 'Nethermind',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Nethermind_8a867227bb.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Nethermind_2ab7275686.webp',
  },
  {
    id: 77,
    companyName: 'Optimism',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Optimism_765c7f3ab3.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Optimism_765c7f3ab3_d3cb33a2a3.webp',
  },
  {
    id: 78,
    companyName: 'Blockchain',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/blockchain_company_logo_91e3d22774.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/blockchain_company_logo_37f66170ff.webp',
  },
  {
    id: 79,
    companyName: 'Findora',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/findora_company_logo_62015114f1.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/findora_company_logo_31df85c1b9.webp',
  },
  {
    id: 80,
    companyName: 'Energi Core Limited',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/energi_core_limited_company_logo_095458775a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/energi_core_limited_company_logo_8b53248230.webp',
  },
  {
    id: 81,
    companyName: 'Coin Metrics',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/coin_metrics_company_logo_d688327ed3.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/coin_metrics_company_logo_29e4069583.webp',
  },
  {
    id: 82,
    companyName: 'Messari',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/messari_company_logo_baa98d22a0.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/messari_company_logo_2f2d8aa550.webp',
  },
  {
    id: 83,
    companyName: 'Textile',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Textile_615f51d110.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Textile_37b8a447cb.webp',
  },
  {
    id: 84,
    companyName: 'Qubit9 Gmb H',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/qubit9_gmb_h_company_logo_807474d05a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/qubit9_gmb_h_company_logo_ac27faaea2.webp',
  },
  {
    id: 85,
    companyName: 'Chronicled.Com',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/chronicled_company_logo_9ec3cc9d2f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/chronicled_company_logo_5e5fc16537.webp',
  },
  {
    id: 86,
    companyName: 'Kronos Research',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/kronos_company_logo_4acc4a8b40.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/kronos_company_logo_ecf210bb46.webp',
  },
  {
    id: 87,
    companyName: 'Brave',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/brave_company_logo_838dca0ed2.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/brave_company_logo_5ea8921dfa.webp',
  },
  {
    id: 88,
    companyName: 'Gluwa',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/gluwa_company_logo_8acdfd8cd9.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/gluwa_company_logo_6f7f87880a.webp',
  },
  {
    id: 89,
    companyName: 'Super Rare Labs',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/super_rare_labs_company_logo_c9d4e4a304.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/super_rare_labs_company_logo_1f5711d704.webp',
  },
  {
    id: 90,
    companyName: 'Unstoppable Finance',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Unstoppable_Finance_570b1f32f2.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Unstoppable_Finance_570b1f32f2_2008483d22.webp',
  },
  {
    id: 91,
    companyName: 'River Financial',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/river_financial_company_logo_87b6275bd7.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/river_financial_company_logo_f07d6667db.webp',
  },
  {
    id: 92,
    companyName: 'Gnosis',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/gnosis_company_logo_7f9c2a1536.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/gnosis_company_logo_cf21ea81e5.webp',
  },
  {
    id: 93,
    companyName: 'Blue Cube Services',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/blue_cube_services_company_logo_3643ed2ad9.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/blue_cube_services_company_logo_659c7c82c8.webp',
  },
  {
    id: 94,
    companyName: 'Crystal Blockchain Analytics',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/crystal_blockchain_analytics_company_logo_a5ef79d376.webp',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/crystal_blockchain_analytics_company_logo_2628096540.webp',
  },
  {
    id: 95,
    companyName: 'Dharma',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Dharma_1e4c0a237a.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/Dharma_a79a696ee1.webp',
  },
  {
    id: 96,
    companyName: 'Metaplex Studios',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/metaplex_company_logo_a8074e0dbb.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/metaplex_company_logo_768b0f03d7.webp',
  },
  {
    id: 97,
    companyName: 'Ftx Us',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/ftx_us_company_logo_f06f6d039f.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/ftx_us_company_logo_651e441939.webp',
  },
  {
    id: 98,
    companyName: 'Voice',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/voice_company_logo_ec9a6a9377.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/voice_company_logo_a8138e6f4e.webp',
  },
  {
    id: 99,
    companyName: 'Boston Protocol',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/boston_protocol_company_logo_25ef770fd4.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/boston_protocol_company_logo_6f1fb0e8a6.webp',
  },
  {
    id: 100,
    companyName: 'Celo Foundation',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/celo_foundations_company_logo_d8e6797e2e.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/celo_foundations_company_logo_a68094833f.webp',
  },
];

export const DEMO_COMPANIES = [
  {
    id: 1,
    companyName: 'Coinbase',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/coinbase_company_logo_0b832f7fce.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/coinbase_company_logo_4e41766ac9.webp',
  },
  {
    id: 2,
    companyName: 'Binance',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/binance_company_logo_82772d9680.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/binance_company_logo_8757bd0823.webp',
  },
  {
    id: 3,
    companyName: 'Near',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/near_company_logo_2a0eb9930d.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/near_company_logo_aea1d13059.webp',
  },
  {
    id: 4,
    companyName: 'GlobalID',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/Globali_D_6abc8eabdc.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/globalid_70eef68a19.webp',
  },
  {
    id: 5,
    companyName: 'Consensys',
    logoUrl: 'https://huntd-files.s3.eu-central-1.amazonaws.com/consensys_company_logo_c428d48fe0.webp',
    devLogoUrl: 'https://huntd-files-development.s3.eu-central-1.amazonaws.com/consensys_company_logo_8b5756c9da.webp',
  },
];
