# https://docs.fastlane.tools/actions
# https://docs.fastlane.tools/plugins/available-plugins

update_fastlane
default_platform(:ios)

platform :ios do
  lane :build do
      build_app(workspace: "Huntd.xcworkspace", scheme: "Huntd")
  end

  lane :beta do
    increment_build_number(xcodeproj: "Huntd.xcodeproj")
    build_app(workspace: "Huntd.xcworkspace", scheme: "Huntd")
    upload_to_testflight
  end

  lane :release do
    increment_build_number(xcodeproj: "Huntd.xcodeproj")
    build_app(workspace: "Huntd.xcworkspace", scheme: "Huntd")
    upload_to_app_store
  end
end
