export const AnalyticsEvents = {
  auth: {
    SignUp: 'sign_up',
    SignIn: 'sign_in',
    JoinPageVisited: 'join_with_code_page_visited',
    JoinCodeSubmitted: 'join_code_submitted',
  },
  cta: {
    CreateAccountClick: 'create_account_btn_click',
    VacanciesClick: 'vacancies_btn_click',
    PricingClick: 'pricing_btn_click',
    SearchCandidatesClick: 'search_candidates_btn_click',
    SignUpLinkClick: 'sign_up_link_click',
    SignInLinkClick: 'sign_in_link_click',
    ViewMoreJobsClick: 'jobs_more_click',
  },
  userProfile: {
    ConnectSocialProviderClick: 'connect_social_provider',
    ActivateProfileClick: 'activate_profile_click',
    ProfileDeactivated: 'profile_deactivated',
  },
  pageInteraction: {
    VisitCandidateProfile: 'visit_candidate_profile',
    ConnectCandidateProfile: 'connect_profile_click',
    ChooseProfileType: 'choose_profile_type',
    FiltersUsed: 'filters_used',
    CvUploaded: 'cv_uploaded',
    ShowMoreButtonClicked: 'show_more_button_clicked',
    AvatarUploaded: 'avatar_uploaded',
    communityButtonClicked: 'community_button_clicked',
    InterestButtonClicked: 'interest_button_clicked',
    VisitPricingPage: 'pricing_page_visited',
    VisitJobsPage: 'jobs_page_visited',
    VisitChatsPage: 'chats_page_visited',
    VisitCompaniesPage: 'companies_page_visited',
    VisitListingPage: 'listing_page_visited',
    VisitSalariesPage: 'salaries_page_visited',
    CvClicked: 'cv_clicked',
  },
  chatInteraction: {
    CandidateOpenContacts: 'candidate_opened_contacts',
    ChatOpened: 'chat_opened',
    MessageSent: 'message_sent',
    MessageUpdated: 'message_updated',
    BulkMessagesSent: 'bulk_messages_sent',
  },
  subscriptions: {
    SubscriptionCreated: 'subscription_created',
    SubscriptionDeleted: 'subscription_deleted',
    SubscriptionUsed: 'subscription_used',
    AutoSubscription: 'auto_subscription',
    SubscriptionsEmailAllClicked: 'subscription_email_all_clicked',
  },
  templates: {
    TemplateCreated: 'template_created',
    TemplateDeleted: 'template_deleted',
    TemplateUsed: 'template_used',
  },
  vacancies: {
    VacancyPostRequested: 'vacancy_post_requested',
    VacancyApplicationRequested: 'vacancy_application_requested',
    VacancyDetailsClicked: 'vacancy_details_clicked',
    SourcedVacancyApply: 'sourced_vacany_apply_clicked',
    ATSTypeChosen: 'ats_type_chosen',
    VacancySubscriptionSent: 'vacancy_subscription_sent',
  },
  companiesLanding: {
    VisitCompaniesLanding: 'companies_landing_visited',
    CompaniesTopButtonClick: 'companies_top_btn_click',
    CompaniesComparisonClick: 'companies_comparison_btn_click',
    CompaniesFomoClick: 'companies_fomo_btn_click',
  },
  appDownloadClicks: {
    GooglePlayClicked: 'google_play_clicked',
    AppStoreClicked: 'app_store_clicked',
  },
  candidateSignUpFlow: {
    SpecialityStep: 'speciality_step',
    ExpectationsStep: 'expectations_step',
    ExperienceStep: 'experience_step',
    ContactsStep: 'contacts_step',
    WorkPlacesStep: 'workplaces_step',
    BioStep: 'bio_step',
  },
  feedbacks: {
    FeedbackButtonClicked: 'feedback_button_clicked',
    FeedbackSubmitted: 'feedback_submitted',
  },
  hirings: {
    HiringStatusCandidateClicked: 'hiring_status_candidate_clicked',
    HiringStatusChanged: 'hiring_status_changed ',
    HiringStatusesSubmitted: 'hiring_statuses_submitted',
    PaymentRequested: 'hiring_pay_clicked',
  },
  workPlaces: {
    ParsedFromLinkedIn: 'parsed_from_linkedin',
    WorkPlaceCreated: 'workplace_created',
    WorkPlaceUpdated: 'workplace_updated',
    WorkPlaceDeleted: 'workplace_deleted',
  },
};
