# https://docs.fastlane.tools/actions
# https://docs.fastlane.tools/plugins/available-plugins

update_fastlane

default_platform(:android)

platform :android do
  def increment_version_code(gradle_build: 'app/build.gradle')
    sh %Q{cd ../ && echo "$(awk '{sub(/versionCode [[:digit:]]+$/,"versionCode "$2+1)}1' #{gradle_build})" > #{gradle_build} && cd -}
  end

  lane :deploy do
    increment_version_code gradle_build: 'app/build.gradle'

    gradle(
      task: "clean assemble",
      build_type: "release"
    )

    upload_to_play_store
  end
end
